"""empty message

Revision ID: 001c041c9c4b
Revises: 
Create Date: 2023-02-09 15:47:53.493002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001c041c9c4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('adult', sa.Boolean(), nullable=True),
    sa.Column('backdrop_path', sa.String(), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('imdb_id', sa.String(), nullable=True),
    sa.Column('original_language', sa.String(), nullable=True),
    sa.Column('original_title', sa.String(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('poster_path', sa.String(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('revenue', sa.Integer(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tagline', sa.String(), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movie_director', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'movie', ['movie_id'], ['id'])

    with op.batch_alter_table('movie_genres', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'movie', ['movie_id'], ['id'])

    with op.batch_alter_table('movie_spoken_languages', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'movie', ['movie_id'], ['id'])

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('popularity', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('popularity')

    with op.batch_alter_table('movie_spoken_languages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('movie_genres', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('movie_director', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('movie')
    # ### end Alembic commands ###
