"""empty message

Revision ID: 1548f525b0ac
Revises: 7a10632f37b0
Create Date: 2023-01-28 04:15:18.709644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1548f525b0ac'
down_revision = '7a10632f37b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
