"""empty message

Revision ID: 29d37d9d5a8a
Revises: c7a9eb8d75af
Create Date: 2023-02-04 20:56:52.398753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d37d9d5a8a'
down_revision = 'c7a9eb8d75af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iso_639_1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('english_name', sa.String(), nullable=True))
        batch_op.drop_column('tmdb_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('english_name')
        batch_op.drop_column('iso_639_1')

    # ### end Alembic commands ###
