"""empty message

Revision ID: 2ec2feb2f6b7
Revises: 4c0b8e9cdd1e
Create Date: 2023-02-06 20:58:48.956230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec2feb2f6b7'
down_revision = '4c0b8e9cdd1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
