"""empty message

Revision ID: 3ed368ee126d
Revises: 2ec2feb2f6b7
Create Date: 2023-02-06 21:00:43.932802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed368ee126d'
down_revision = '2ec2feb2f6b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
