"""empty message

Revision ID: 408e06a094fc
Revises: 573ff2b2f643
Create Date: 2023-01-25 00:54:56.588633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408e06a094fc'
down_revision = '573ff2b2f643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.drop_column('email')
        batch_op.drop_column('password')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
