"""empty message

Revision ID: 6f6f118ddc70
Revises: cfb0cbc30d92
Create Date: 2023-02-04 22:11:50.501478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f6f118ddc70'
down_revision = 'cfb0cbc30d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_spoken_languages',
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('language_id', 'movie_id')
    )
    op.drop_table('movie_languages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_languages',
    sa.Column('language_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], name='movie_languages_language_id_fkey'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='movie_languages_movie_id_fkey'),
    sa.PrimaryKeyConstraint('language_id', 'movie_id', name='movie_languages_pkey')
    )
    op.drop_table('movie_spoken_languages')
    # ### end Alembic commands ###
