"""empty message

Revision ID: 796cf8eda7f7
Revises: f595cfd3870d
Create Date: 2023-01-30 20:52:59.496746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796cf8eda7f7'
down_revision = 'f595cfd3870d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('tmdb_id')

    # ### end Alembic commands ###
