"""empty message

Revision ID: 8341ea6f970f
Revises: 001c041c9c4b
Create Date: 2023-02-09 16:38:23.807333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8341ea6f970f'
down_revision = '001c041c9c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_cast',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'movie_id')
    )
    op.create_table('movie_crew',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'movie_id')
    )
    op.drop_table('movie_director')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_director',
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='movie_director_movie_id_fkey'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name='movie_director_person_id_fkey'),
    sa.PrimaryKeyConstraint('person_id', 'movie_id', name='movie_director_pkey')
    )
    op.drop_table('movie_crew')
    op.drop_table('movie_cast')
    # ### end Alembic commands ###
