"""empty message

Revision ID: a326646d3b8f
Revises: 52fdd4395f6b
Create Date: 2023-01-29 05:50:05.631785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a326646d3b8f'
down_revision = '52fdd4395f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
