"""empty message

Revision ID: ba7e5e45d2a1
Revises: 18aeeca50e25
Create Date: 2023-02-11 17:38:13.526868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7e5e45d2a1'
down_revision = '18aeeca50e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.drop_column('tmdb_id')

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_column('tmdb_id')

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('tmdb_id')

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('tmdb_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_id', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_id', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_id', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_id', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
