"""empty message

Revision ID: e138917a3e8c
Revises: 
Create Date: 2023-02-11 19:50:24.718952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e138917a3e8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('iso_639_1', sa.String(), nullable=True),
    sa.Column('english_name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie',
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('adult', sa.Boolean(), nullable=True),
    sa.Column('backdrop_path', sa.String(), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('imdb_id', sa.String(), nullable=True),
    sa.Column('original_language', sa.String(), nullable=True),
    sa.Column('original_title', sa.String(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('poster_path', sa.String(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('revenue', sa.Integer(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tagline', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('birthday', sa.String(), nullable=True),
    sa.Column('known_for_department', sa.String(), nullable=True),
    sa.Column('deathday', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('biography', sa.String(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('place_of_birth', sa.String(), nullable=True),
    sa.Column('profile_path', sa.String(), nullable=True),
    sa.Column('adult', sa.Boolean(), nullable=True),
    sa.Column('imdb_id', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_cast',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'movie_id')
    )
    op.create_table('movie_crew',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'movie_id')
    )
    op.create_table('movie_genres',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('genre_id', 'movie_id')
    )
    op.create_table('movie_spoken_languages',
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('language_id', 'movie_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_spoken_languages')
    op.drop_table('movie_genres')
    op.drop_table('movie_crew')
    op.drop_table('movie_cast')
    op.drop_table('comment')
    op.drop_table('user')
    op.drop_table('person')
    op.drop_table('movie')
    op.drop_table('log')
    op.drop_table('language')
    op.drop_table('genre')
    # ### end Alembic commands ###
